[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
;we need to use esp32dev here if we are not going to use esp32cam
board = esp32cam
framework = arduino
lib_deps = bblanchon/ArduinoJson@^6.21.3

; Serial Monitor Config
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

; Build Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Partition Table
board_build.partitions = huge_app.csv
